#!/usr/bin/env node
// Apify -> Airtable normalizer CLI.
//
//   node apify-harvest.js --channel-url <url> --max-results 5 --oldest-post-date 2026-07-01 [--dry-run]
//
// Design decisions this implements (see repo CLAUDE.md "Active work" for the
// full rationale — this comment only covers what's enforced in code):
//
//   - --max-results and --oldest-post-date are MANDATORY on every run,
//     dry-run or not. No unbounded channel pulls. (Guardrail.)
//   - Queue-depth ceiling: refuses to run while Triage Status=Queued count
//     in Airtable is already at/above --queue-ceiling (default 30).
//   - --dry-run performs all reads (Apify call + Airtable existence checks)
//     but no writes, and prints exactly what it would have written.
//   - Reuses chrome-extension/lib/transcript-utils.js for GH-64 truncation,
//     and the write invariants from background.js (upsert by Video ID,
//     never touch Triage Status on update, Channel found/created by
//     Channel Handle = channelId).
//
// KNOWN GAP (2026-07-29): --oldest-post-date is passed to the actor as
// "oldestPostDate", per the repo CLAUDE.md's assumed input schema. That
// field name has only been inferred, never confirmed against a real
// channel-mode (as opposed to single-video) Apify run. Before the first
// real (non-dry-run) sweep against a channel, do one --dry-run against a
// real channel URL and inspect the printed Apify input/output to confirm
// the actor actually respects this field — otherwise a "bounded" sweep
// could silently pull the whole channel history.

const fs = require('node:fs');
const path = require('node:path');

const { runActorSync } = require('./lib/apify-client');
const { buildVideoFields } = require('./lib/transform');
const { countQueued, upsertChannel, upsertVideo } = require('./lib/airtable-client');

function loadDotEnv() {
  const envPath = path.join(__dirname, '..', '.env');
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const match = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line.trim());
    if (match && !process.env[match[1]]) process.env[match[1]] = match[2];
  }
}

function parseArgs(argv) {
  const args = { dryRun: false, queueCeiling: 30 };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    switch (arg) {
      case '--channel-url':
        args.channelUrl = argv[++i];
        break;
      case '--max-results':
        args.maxResults = Number(argv[++i]);
        break;
      case '--oldest-post-date':
        args.oldestPostDate = argv[++i];
        break;
      case '--queue-ceiling':
        args.queueCeiling = Number(argv[++i]);
        break;
      case '--dry-run':
        args.dryRun = true;
        break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return args;
}

function validateArgs(args) {
  const errors = [];
  if (!args.channelUrl) errors.push('--channel-url is required');
  if (!args.maxResults || args.maxResults <= 0) errors.push('--max-results is required and must be > 0 (guardrail: no unbounded pulls)');
  if (!args.oldestPostDate) errors.push('--oldest-post-date is required (guardrail: no unbounded pulls) — format YYYY-MM-DD');
  if (errors.length) {
    throw new Error(`Invalid arguments:\n  - ${errors.join('\n  - ')}`);
  }
}

async function main() {
  loadDotEnv();
  const args = parseArgs(process.argv.slice(2));
  validateArgs(args);

  const apifyToken = process.env.APIFY_TOKEN;
  const airtableKey = process.env.AIRTABLE_API_KEY;
  const baseId = process.env.AIRTABLE_BASE_ID;

  if (!apifyToken) throw new Error('APIFY_TOKEN not set (.env)');
  if (!airtableKey || !baseId) throw new Error('AIRTABLE_API_KEY / AIRTABLE_BASE_ID not set (.env)');

  console.log(`[queue check] querying Triage Status=Queued count...`);
  const queuedCount = await countQueued(airtableKey, baseId);
  console.log(`[queue check] ${queuedCount} currently Queued (ceiling: ${args.queueCeiling})`);
  if (queuedCount >= args.queueCeiling) {
    console.error(`Refusing to harvest: Queued count (${queuedCount}) is at/above the ceiling (${args.queueCeiling}). The refinery's bottleneck is the human review gate, not capture — clear the queue before sweeping more in.`);
    process.exitCode = 1;
    return;
  }

  const input = {
    startUrls: [{ url: args.channelUrl }],
    maxResults: args.maxResults,
    oldestPostDate: args.oldestPostDate, // UNVERIFIED field name — see header comment
    downloadSubtitles: true,
    subtitlesFormat: 'srt',
    preferAutoGeneratedSubtitles: true,
    saveSubsToKVS: false, // inline delivery confirmed sufficient — see srt-parser.js
  };

  console.log(`[apify] running actor with input:`, JSON.stringify(input, null, 2));
  const items = await runActorSync({ token: apifyToken, input });
  console.log(`[apify] dataset returned ${items.length} item(s)`);

  const summary = { created: 0, updated: 0, wouldCreate: 0, wouldUpdate: 0, skipped: 0, channelsCreated: 0 };

  for (const item of items) {
    const built = buildVideoFields(item);
    if (built.skipped) {
      console.warn(`[skip] ${item?.id || '(no id)'}: ${built.skipped}`);
      summary.skipped++;
      continue;
    }

    for (const warning of built.warnings) {
      console.warn(`[warn] ${built.videoId}: ${warning}`);
    }

    const channelResult = await upsertChannel(airtableKey, baseId, built.channel, { dryRun: args.dryRun });
    if (channelResult.created) {
      summary.channelsCreated++;
      console.warn(`[channel] created "${built.channel.channelName}" with NO Track set — it will silently vanish from the working view (Track = AIHS OR Tooling-watch) until someone sets Track by hand.`);
    }

    const videoResult = await upsertVideo(
      airtableKey,
      baseId,
      {
        videoId: built.videoId,
        channelRecordId: channelResult.recordId,
        createOnlyFields: built.createOnlyFields,
        updateFields: built.updateFields,
      },
      { dryRun: args.dryRun }
    );

    console.log(`[video] ${built.videoId} (${built.createOnlyFields['Video Title']}): ${videoResult.action}`);
    if (videoResult.action === 'created') summary.created++;
    else if (videoResult.action === 'updated') summary.updated++;
    else if (videoResult.action === 'would-create') summary.wouldCreate++;
    else if (videoResult.action === 'would-update') summary.wouldUpdate++;
  }

  console.log('\n[summary]', JSON.stringify(summary, null, 2));
  if (args.dryRun) console.log('\nDry run — nothing was written to Airtable.');
}

main().catch((error) => {
  console.error(`\nError: ${error.message}`);
  process.exitCode = 1;
});
